#Acessing another property in same yaml file   
my:
  app:
    desc: My app ${spring.application.name} is demo app
    #greeting: Welcome here
    dummynumbers: one,two,three #Mapping list to key 
    users: '{user1:''abhi'', user2:''kiran'', user3:''aman''}'  #Mapping Map to single Key
