server:
  port: 8092
  
my:
  app:
    desc: I am from microservice specific configuration file, My app is demo app
    
#Below properties are examples to demo @ConnectionProperties in different config class    
db:
  connection: '{connectionString:''http/demo-connection'', userName:''abhi'', password:''test''}'
  host: 3000
  dbname: oracle
