server:
  port: 8092
  
my:
  app:
    desc: I am from spring-config-demo microservice specific configuration file i.e. spring-config-demo.yml. Chnage one more time. 
  
#Below properties are examples to demo @ConnectionProperties in different config class    
db:
  connection: connection-string-from-config-server-updated
  host: 127.0.0.1
  port: 1200
